---
development:
  cloud_name: diquwvmgb
  api_key: '359996774154646'
  api_secret: "-nA4_QsqWN77vsqvZbaPwRnht9U"
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: diquwvmgb
  api_key: '359996774154646'
  api_secret: "-nA4_QsqWN77vsqvZbaPwRnht9U"
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: diquwvmgb
  api_key: '359996774154646'
  api_secret: "-nA4_QsqWN77vsqvZbaPwRnht9U"
  enhance_image_tag: true
  static_file_support: false
